### ISSUE TITLE
Theme detail: improve format of overview data

### ISSUE THREAD

**Issue by tuxpiper** [project-pheme/project-pheme-platform-client#16]
![screen shot 2016-08-03 at 22 17 29 copy](https://cloud.githubusercontent.com/assets/467393/17380924/bb46f804-59c9-11e6-853e-f791a9578e23.png)

**Comment by tuxpiper** [comment]
@stephengacheru  FYI there's an additional field in this data now, it's named "Controversiality" and it's a number between 0.0 and 1.0 . If you had a place to put it, that would be great.

We can display the number itself by now, and make the display more interesting later (i.e. with icons or color codes)

**Comment by stephengacheru** [comment]
@tuxpiper Yeah I saw that on the `pheme-theme-list.html`

**Comment by tuxpiper** [comment]
Oh right, I forgot I had added it there. One of the few times when I pleasantly surprise myself.

Thanks!
