### ISSUE TITLE
Theme detail: improve format of linked images

### ISSUE THREAD

**Issue by tuxpiper** [project-pheme/project-pheme-platform-client#18]
![screen shot 2016-08-03 at 22 17 45](https://cloud.githubusercontent.com/assets/467393/17381244/48aadf34-59cb-11e6-90c8-e17dfe72b891.png)

**Comment by tuxpiper** [comment]
some updates here @stephengacheru : text for the images is going to be dropped, and we are going to try to eliminate duplicates. Because of that, each image will have a count of how many times it appears.

**Comment by stephengacheru** [comment]
Ok great! That makes things easier
