### ISSUE TITLE
[Topics] Remove useless empty grey header area on the right hand side

### ISSUE THREAD

**Issue by tuxpiper** [project-pheme/project-pheme-platform-client#24]
![screen shot 2017-01-09 at 18 48 55](https://cloud.githubusercontent.com/assets/467393/21776768/6d7c37f6-d69c-11e6-8a62-08e32953c013.png)

**Comment by sethburtonhall** [comment]
@tuxpiper can you provide a screenshot of the specific area?

**Comment by tuxpiper** [comment]
@middle8media  sorry about that, done
