### ISSUE TITLE
Increase contrast between two hues of the palette

### ISSUE THREAD

**Issue by tuxpiper** [project-pheme/project-pheme-platform-client#49]
@middle8media could we increase contrast between these two colors?

![6346e3dc-e3ba-11e6-8fd7-1b14b0e550de](https://cloud.githubusercontent.com/assets/467393/22562767/365be2d6-e97e-11e6-8be9-c8dabb2b8f9a.png)

**Comment by sethburtonhall** [comment]
fixes via https://github.com/project-pheme/project-pheme-pattern-library/commit/85121b200b85d6d9dfc8e8f6f066b5a90c063305
