### ISSUE TITLE
Avoid using red, green, yellow for topic colors

### ISSUE THREAD

**Issue by tuxpiper** [project-pheme/project-pheme-platform-client#50]
Due to concerns of the users attaching some sort of meaning to them.
![screen shot 2017-02-02 at 19 32 10](https://cloud.githubusercontent.com/assets/467393/22562872/a2c50132-e97e-11e6-8100-7ce40b110ba5.png)

**Comment by sethburtonhall** [comment]
Fixed via https://github.com/project-pheme/project-pheme-platform-client/commit/e63e2bdda3bba73a636b16dd10aecfed640e680a

We can adjust colors as needed.
