### ISSUE TITLE
Excessive blank space on right hand side of pheme card and pheme detail metadata

### ISSUE THREAD

**Issue by tuxpiper** [project-pheme/project-pheme-platform-client#51]
Looks like we could better adjust to wider displays

![screen shot 2017-02-02 at 19 35 20](https://cloud.githubusercontent.com/assets/467393/22562923/d981e5f0-e97e-11e6-9c71-51c7c88d15ce.png)

![screen shot 2017-02-02 at 19 39 42](https://cloud.githubusercontent.com/assets/467393/22563080/7baadfa8-e97f-11e6-9278-d355dff9a617.png)

**Comment by tuxpiper** [comment]
@middle8media  I think I'm still seeing this behaviour in the pheme cards ( https://github.com/project-pheme/project-pheme-platform-client/blob/master/server/www/templates/pheme/card.html#L7 )

![screen shot 2017-02-07 at 12 36 24](https://cloud.githubusercontent.com/assets/467393/22689754/b049d672-ed32-11e6-8751-432bc30191ca.png)

Could you please verify the fix?

**Comment by sethburtonhall** [comment]
Do we still need to consider this? If not, we can just close?

**Comment by tuxpiper** [comment]
Yea we can close this now.
